
// SlkParse.h - generated by the SLK parser generator 

#ifndef _SlkPARSE_H
#define _SlkPARSE_H

namespace quan_lexer {

   /*
      Tokens are integers
      Any value less than 256 
   */

   enum _Slk_token_defines { 
     
     NAME_ = 257 
   , EMIT_ = 258 
   , JUMP_ = 259 
   , APPEND_ = 260 
   , PUSHFPOS_ = 262 
   , POPFPOS_ = 263 
   , STRING_LITERAL_ = 264  
   , DEFAULT_ = 266 
   , STATE_ = 267 
   , DOT_DOT_ = 268 
   , CHARSEQ_ = 269 
   , END_OF_INPUT = 270 
   , UNDEFINED = 271
   }; 
}


#endif
