
// SlkParse.h - generated by the SLK parser generator 

#ifndef _SlkPARSE_H
#define _SlkPARSE_H

namespace quan_lexer {

   enum _Slk_token_defines { 
     NAME_ = 257 
   , EMIT_ = 258 
   , JUMP_ = 259 
   , APPEND_ = 260 
   , PUSHFPOS_ = 262 
   , POPFPOS_ = 263 
   , STRING_LITERAL_ = 264 
   , CHAR_ = 265 
   , DEFAULT_ = 266 
   , STATE_ = 267 
   , DOT_DOT_ = 268 
   , CHARSEQ_ = 269 
   , END_OF_SLK_INPUT_ = 270 
   }; 
}


#endif
