
// SlkParse.h - generated by the SLK parser generator 

#ifndef _SlkPARSE_H
#define _SlkPARSE_H

//#include "SlkLog.h"
//#include "SlkToken.h"
//#include "SlkError.h"
//#include "SlkAction.h"
// clude "SlkTree.h"
 
namespace quan_lexer {

enum _Slk_token_defines { 
  NAME_ = 257 
, EMIT_ = 258 
, JUMP_ = 259 
, APPEND_ = 260 
, PUSHFPOS_ = 262 
, POPFPOS_ = 263 
, STRING_LITERAL_ = 264 
, CHAR_ = 265 
, DEFAULT_ = 266 
, STATE_ = 267 
, DOT_DOT_ = 268 
, CHARSEQ_ = 269 
, END_OF_SLK_INPUT_ = 270 
}; 

/*
enum _Slk_Nonterminal_defines { 
  NT_FLEXER_ = 2049 
, NT_FLEXER_OR_MODE_DECL_ = 2050 
, NT_FLEXER_DECL_ = 2051 
, NT_ACTION_EXPR_ = 2052 
, NT_RETURN_VALUE_ = 2053 
, NT_ACTION_IMPL_ = 2054 
, NT_APPEND_ARGS_ = 2055 
, NT_ACTION_LIST_ = 2056 
, NT_MODE_DECL_ = 2057 
, NT_MODE_DECL_CONTINUE_ = 2058 
, NT_MODE_BODY_ = 2059 
, NT_DEFINITION_ = 2060 
, NT_BASIC_PRIM_ = 2061 
, NT_PRIM_ = 2062 
, NT_PRIM_MODIFIER_ = 2063 
, NT_AND_EXPR_ = 2064 
, NT_SEQ_EXPR_ = 2065 
, NT_EXPR_ = 2066 
, NT_FLEXER_OR_MODE_DECL_STAR_ = 2067 
, NT_ACTION_LIST_OPT_ = 2068 
, NT_COMMA_ACTION_IMPL_STAR_ = 2069 
, NT_FLEXER_DECL_STAR_ = 2070 
, NT_DOT_DOT_CHAR_OPT_ = 2071 
, NT_PRIM_MODIFIER_OPT_ = 2072 
, NT_AND_PRIM_STAR_ = 2073 
, NT_AND_EXPR_STAR_ = 2074 
, NT_OR_SEQ_EXPR_STAR_ = 2075 
}; 

enum _Slk_symbol_type_defines { 
  NOT_A_SYMBOL       = 0
, NONTERMINAL_SYMBOL = 1
, TERMINAL_SYMBOL    = 2
, ACTION_SYMBOL      = 3
}; 

int SlkGetSymbolType ( short symbol );
int SlkIsNonterminal ( short symbol );
int SlkIsTerminal ( short symbol );
int SlkIsAction ( short symbol );
short SlkGetTerminalIndex ( short   token );

//void SlkParse ( int         display,
//                SlkAction  &action, 
//                SlkToken   &tokens, 
//                SlkError   &error, 
//                SlkLog     &log, 
//                // Tree    &tree,
//                short       start_symbol ) ;
//
//
//
*/
}


#endif
