
// SlkParse.h - generated by the SLK parser generator 

#ifndef FLEXIBLE_TOKEN_ID_HPP
#define FLEXIBLE_TOKEN_ID_HPP

namespace quan_lexer {

   /*
      Tokens are integers
      Any value less than 256 may be used for char ids
      value 256 represenst end of input
      value 257 represents undefined
      values below 300 are reserved
   */

   enum TokenID { 
     NAME_ = 300
   , EMIT_ 
   , JUMP_  
   , APPEND_ 
   , PUSHFPOS_ 
   , POPFPOS_  
   , STRING_LITERAL_  
   , DEFAULT_
   , STATE_ 
   , DOT_DOT_ 
   , CHARSEQ_
   , CHAR
   , EMPTY_SET
   }; 
}


#endif //FLEXIBLE_TOKEN_ID_HPP
